### PR TITLE
Feature/style comparison modal

### PR DESCRIPTION
**Pull request by acdavitt**
@julia-thea @ChrisRPeterson @dylanreid7 
--Quick bug fix for extra padding on RelatedProductCards (removed CardAction)
--Added styling to the ComparisonModal.  Open to any suggestions for additional styling.

### CODE REVIEW

**Review by julia-thea — APPROVED** [review]
Glad to see cards rendering with the nice space between them  -- so pretty🌸💐🌷

As far as styling suggestions for the comparison modal -- and it's just my preference -- I'd suggest plain background rather than default pink. 
How about using default pink for the header color instead? Would be consistent with the general app styling we currently have.
The modal style feels a bit heavy with the current colors. 

Another suggestion -- how about moving params by which items are compared to the left side?

@acdavitt

**Comment by acdavitt** [comment]
@julia-thea Good idea changing the background to white and using the pink for the header!  I agree it feels heavy.  Will definitely implement that change!  As for the params, I think I have to leave the order as is per the business requirement doc: "These characteristics should appear in a table format with the first column representing the product for the current page, the second displaying the characteristic, and the third representing the product to be compared."

**Comment by acdavitt** [comment]
@julia-thea Color changes implemented!  Looks much better with your suggestion!  What do you think about the lines between the rows?  OK to leave in or would it look better without?

**Comment by julia-thea** [comment]
@acdavitt it looks so clean! I think lines make sense here and help to see the row clearly.
Another suggestion, may be make everything a bit smaller -- both modal itself and the text size of compared products?
Only if it's not too much work, because it looks pretty good as is.

**Comment by acdavitt** [comment]
@julia-thea No problem at all!  I decreased the modal size and font size.  Currently I have the actual characteristics slightly larger for each product to help differentiate between them (e.g. canvas, 100% cotton) and feature name (eg. fabric) slightly smaller, but bolded in the middle.  Not sure if this looks odd or not?  Should I make them all the same size for all 3 columns?

**Comment by julia-thea** [comment]
@acdavitt I feel like the same size would look really good while keeping bold font in the middle column and regular on actual characteristic. That would be my last suggestion.

**Comment by acdavitt** [comment]
@julia-thea Changed the font size so that all columns are the same.  Thanks so much for all your wonderful suggestions!  The modal looks so much better!!

**Comment by julia-thea** [comment]
@acdavitt So happy to hear that. You are most welcome

**Pull request merged**
